

#         Powered by TabooLib 5.0         #

# 未经本插件作者允许，任何人无权再发布本插件 #

name: ${name}
main: ${main}
version: ${version}
authors: ['贺兰星辰']

lib-download: true
lib-version: ${libVersion}
api-version: 1.13